"""add_bio_is_active_to_users

Revision ID: d0d2b217ce59
Revises: 
Create Date: 2026-09-04 15:27:32.817802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d2b217ce59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — adds bio and is_active columns to users table.

    Effect on existing data:
    - bio: all existing rows get NULL (nullable column, safe)
    - is_active: all existing rows get TRUE (server_default='true', safe)

    Rollback: run `alembic downgrade -1` to remove both columns.
    """
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('true'),  # existing rows get TRUE
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
